[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  ROLLUP_SKIP_NATIVE = "true"
  LIGHTNINGCSS_SKIP_NATIVE = "true" 